<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Ajay3147361" name="lalaTestNGTest" tests="23" failures="2" timestamp="29 Nov 2018 13:40:03 GMT" time="4.583" errors="0">
  <testcase name="verifyFutureOrder" time="1.341" classname="com.lala.test.PlaceOrderTest">
    <failure type="java.lang.AssertionError" message="Test is failed, Error while placing order, Please check by placing order manually.">
      <![CDATA[java.lang.AssertionError: Test is failed, Error while placing order, Please check by placing order manually.
	at com.lala.test.PlaceOrderTest.verifyFutureOrder(PlaceOrderTest.java:73)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- verifyFutureOrder -->
  <testcase name="verifyNewOrder" time="1.389" classname="com.lala.test.PlaceOrderTest"/>
  <testcase name="verifyNewOrderWithInvalidPayload" time="0.029" classname="com.lala.test.PlaceOrderTest"/>
  <testcase name="verifyFetchOrderForNewOrder" time="0.302" classname="com.lala.test.FetchOrderTest"/>
  <testcase name="verifyFetchOrderWhenOrderDoesNotExist" time="0.017" classname="com.lala.test.FetchOrderTest"/>
  <testcase name="verifyFetchOrderWhenOrderExist" time="0.02" classname="com.lala.test.FetchOrderTest"/>
  <testcase name="verifyDriveToTakeAlreadyCancelledOrder" time="0.018" classname="com.lala.test.DriveToTakeOrderTest"/>
  <testcase name="verifyDriveToTakeAlreadyCompletedOrder" time="0.015" classname="com.lala.test.DriveToTakeOrderTest"/>
  <testcase name="verifyDriveToTakeAlreadyOnGoingOrder" time="0.015" classname="com.lala.test.DriveToTakeOrderTest"/>
  <testcase name="verifyDriveToTakeExistingOrder" time="0.013" classname="com.lala.test.DriveToTakeOrderTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.lala.test.DriveToTakeOrderTest.verifyDriveToTakeExistingOrder(DriveToTakeOrderTest.java:76)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- verifyDriveToTakeExistingOrder -->
  <testcase name="verifyDriveToTakeOnOrderDoesNotExist" time="0.015" classname="com.lala.test.DriveToTakeOrderTest"/>
  <testcase name="verifyDriveToTakeOrder" time="0.459" classname="com.lala.test.DriveToTakeOrderTest"/>
  <testcase name="verifyDriveToCompleteForCancelOrder" time="0.015" classname="com.lala.test.DriveToCompleteOrderTest"/>
  <testcase name="verifyDriveToCompleteForCompletedOrder" time="0.024" classname="com.lala.test.DriveToCompleteOrderTest"/>
  <testcase name="verifyDriveToCompleteForNewOrder" time="0.356" classname="com.lala.test.DriveToCompleteOrderTest"/>
  <testcase name="verifyDriveToCompleteForNonExistingOrder" time="0.013" classname="com.lala.test.DriveToCompleteOrderTest"/>
  <testcase name="verifyDriveToCompleteForOnderOnAssignedState" time="0.013" classname="com.lala.test.DriveToCompleteOrderTest"/>
  <testcase name="verifyCancelExistingOrder" time="0.016" classname="com.lala.test.CancelOrderTest"/>
  <testcase name="verifyCancelNewOrder" time="0.404" classname="com.lala.test.CancelOrderTest"/>
  <testcase name="verifyCancelNonExistingOrder" time="0.012" classname="com.lala.test.CancelOrderTest"/>
  <testcase name="verifyCancelOrderForAlreadyCancelledOrder" time="0.017" classname="com.lala.test.CancelOrderTest"/>
  <testcase name="verifyCancelOrderForCompletedOrder" time="0.014" classname="com.lala.test.CancelOrderTest"/>
  <testcase name="verifyCancelOrderForOnGoingOrder" time="0.017" classname="com.lala.test.CancelOrderTest"/>
</testsuite> <!-- lalaTestNGTest -->
