<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Ajay3147361" name="lalaTestNGTest" tests="3" failures="1" timestamp="20 Nov 2018 10:47:54 GMT" time="2.116" errors="0">
  <testcase name="verifyCancelOrder" time="1.681" classname="com.lala.test.CancelOrderTest"/>
  <testcase name="verifyFutureOrder" time="0.179" classname="com.lala.test.PlaceOrderTest">
    <failure type="java.lang.AssertionError" message="Test is failed, Error while placing order, please check server connection.">
      <![CDATA[java.lang.AssertionError: Test is failed, Error while placing order, please check server connection.
	at com.lala.test.PlaceOrderTest.verifyFutureOrder(PlaceOrderTest.java:78)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- verifyFutureOrder -->
  <testcase name="verifyNewOrder" time="0.231" classname="com.lala.test.PlaceOrderTest"/>
</testsuite> <!-- lalaTestNGTest -->
